resources:
- name: terraform-release
  type: github-release
  source:
    owner: hashicorp
    repository: terraform
    access_token: ((github-access-token)) 
- name: master-branch
  type: git
  source:
    username: ((github-username))
    access_token: ((github-access-token)) 
    uri: https://github.com/brandocorp/concourse-terraform-toolchain.git
    branch: master
- name: terraform-toolchain-image
  type: docker-image
  source:
    repository: brandocorp/concourse-terraform-toolchain
    username: ((docker-username))
    password: ((docker-password))

jobs:
- name: build
  plan:
  - get: master-branch
    trigger: true
  - get: terraform-release
    trigger: true
  - task: download-terraform-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: latest
      inputs:
      - name: master-branch
      - name: terraform-release
      outputs:
      - name: binary
      run:
        path: sh
        args:
        - -ec
        - |
          echo '{"TERRAFORM_VERSION":"$(cat terraform-release/version)"}' | tee master-branch/version.json
  - put: terraform-toolchain-image
    params:
      build: master-branch
      build_args_file: master-branch/version.json
      tag_as_latest: true
