resources:
- name: terraform-release
  type: github-release
  source:
    owner: hashicorp
    repository: terraform
    access_token: ((github-access-token)) 
- name: master-branch
  type: git
  source:
    username: ((github-username))
    access_token: ((github-access-token)) 
    uri: https://github.com/brandocorp-concourse/concourse-terraform-toolchain.git
    branch: master
- name: terraform-toolchain-image
  type: docker-image
  source:
    repository: brandocorp/concourse-terraform-toolchain
    username: ((docker-username))
    password: ((docker-password))

jobs:
- name: build
  plan:
  - get: master-branch
    trigger: true
  - get: terraform-release
    trigger: true
  - task: process-terraform-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: brandocorp/concourse-ubuntu-build
          tag: latest
      inputs:
      - name: master-branch
      - name: terraform-release
      outputs:
      - name: master-version
      run:
        path: sh
        args:
        - -ec
        - |
          git clone master-branch master-version
          echo '{"TERRAFORM_VERSION":"'$(cat terraform-release/version)'"}' | tee master-version/tf.json
  - put: terraform-toolchain-image
    params:
      build: master-version
      build_args_file: master-version/tf.json
      tag_file: master-version/version
      tag_as_latest: true
